version: "3.7"
services:
  redis:
    image: redis:6-alpine3.13
    container_name: redis
  polkadot-tunnel:
    build: polkadot
    image: polkadot-tunnel:latest
    container_name: polkadot-tunnel
    tty: true
    ports: 
      - 9944:9944
    volumes:
      - ~/.ssh:/root/.ssh
  polkaview:
    build: .
    image: polkaview:latest
    command: npm run dev
    container_name: polkaview
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app 
