version: "3"

networks:
  db:
    external: true

volumes:
  redis-data:

services:
  redis:
    image: redis:6-alpine3.13
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - db

  polkaview:
    build: .
    image: polkaview:latest
    command: npm run dev
    container_name: polkaview
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app 
    networks:
      - db

