version: '3'

networks:
    web:
        external: true

volumes:
    redis-data:

services:
    redis:
        image: redis:6-alpine3.13
        container_name: redis
        volumes:
            - redis-data:/data
        networks:
            - web

    traefik:
        container_name: traefik
        image: traefik:v2.2
        labels:
            - traefik.enable=true
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/traefik.toml
            - ./traefik/traefik_dynamic.toml:/traefik_dynamic.toml
            - ./traefik/acme.json:/acme.json # be sure to chmod 600 acme.json
        networks:
            - web

    polkaview:
        build: 
          context: .
          dockerfile: Dockerfile-prod
        image: polkaview:latest
        labels:
            - traefik.enable=true
            - traefik.http.routers.polkadot.rule=Host(`polkaview.network`)
            - traefik.http.routers.polkadot.tls=true
            - traefik.http.routers.polkadot.tls.certresolver=lets-encrypt
            - traefik.http.services.polkadot.loadbalancer.server.port=3000
        command: npm run dev
        container_name: polkaview
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - redis
        volumes:
            - ./:/usr/src/app
        networks:
            - web
