version: "3"
services:
  redis:
    image: redis:6-alpine3.13
    container_name: redis
    volumes:
      - redis-data:/data
  polkaview:
    build: .
    image: polkaview:latest
    command: npm run dev
    container_name: polkaview
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app 
